spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:db;MODE=MYSQL;
      username: sa
      password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true